import type { Event, Message } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    creator_id: 'user123',
    name: "John & Sarah's Wedding",
    description: 'Our special day in New York',
    banner_image: 'events/1/banner/wedding-ceremony.jpg',
    welcome_message: 'Welcome to our wedding!',
    submission_start_date: '2025-06-01T00:00:00.000Z',
    submission_end_date: '2025-07-01T00:00:00.000Z',
    message_count: 12,
    created_at: Date.now(),
    updated_at: Date.now(),
    deleted_at: 0,
    qr_code_key: 'events/1/qr/qr-code.png',
    final_video_key: undefined,
    package: 'premium',
    payment_status: 'success',
  },
  {
    id: '2',
    creator_id: 'user123',
    name: 'Anniversary Party',
    description: '10 years of love and happiness',
    banner_image: 'events/2/banner/anniversary-cake.jpg',
    welcome_message: 'Thanks for celebrating with us!',
    submission_start_date: '2025-08-15T00:00:00.000Z',
    submission_end_date: '2025-09-15T00:00:00.000Z',
    message_count: 5,
    created_at: Date.now(),
    updated_at: Date.now(),
    deleted_at: 0,
    qr_code_key: 'events/2/qr/qr-code.png',
    final_video_key: undefined,
    package: 'basic',
    payment_status: 'success',
  },
];

export const mockMessages: Message[] = [
  {
    id: '101',
    event_id: '1',
    guest_name: 'Mike Johnson',
    media_type: 'video',
    media_key: 'events/1/messages/video/message101.webm',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '102',
    event_id: '1',
    guest_name: 'Emma Thompson',
    media_type: 'audio',
    media_key: 'events/1/messages/audio/message102.webm',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
];
